import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { digest, snapshot, scoreJob, reviewDraft, patchDraft, addManualEvent, cohortMetrics, encryptState, decryptState, withVault, readKey, DIMENSIONS } from '../skills/job-search-agent/scripts/job-agent.mjs';

const user='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const terms=['Python 数据清洗','参与工具开发','应届生','课程项目','广州实习','职业方向'];
const source=terms.join('；'),hash=digest(source),jobid=id(20),version=id(21);
const facts=terms.map((text,i)=>({id:id(i+1),user_id:user,text,project_id:'project-a',source_ref:'synthetic-resume',kind:'experience',polarity:'positive',status:'confirmed'}));
const job={id:jobid,user_id:user,source_kind:'user_provided',source_text:source,
 jd:{job_version_id:version,raw_sha256:hash,source_text_sha256:hash,language:'zh',requirements:terms.map((t,i)=>({requirement_id:'r'+i,kind:'skill',priority:i===0?'must_have':'preferred',value:t,certainty:'explicit',source_span:{source_text_sha256:hash,start:Array.from(source.slice(0,source.indexOf(t))).length,end:Array.from(source.slice(0,source.indexOf(t)+t.length)).length,quote:t}})),salary:null,deadline:null,unknowns:[],warnings:[]},
 evidence:{job_version_id:version,fact_snapshot_hash:snapshot(facts),preference_version_id:id(22),scoring_version:'v0.3',items:Object.keys(DIMENSIONS).map((dimension,i)=>({evidence_item_id:'e'+i,dimension,requirement_id:'r'+i,fact_ids:[id(i+1)],evidence_state:'supported',match_level:1,brief_reason:'Synthetic confirmed evidence',missing_information:[]})),warnings:[]},
 rules:{items:Object.entries(DIMENSIONS).map(([dimension,weight],i)=>({requirement_id:'r'+i,dimension,weight})),hard_checks:[{rule_id:'h1',requirement_id:'r0',critical:true}]},draft:null,section_projects:{s1:'project-a'}};
const confirmations=Object.fromEntries(job.evidence.items.map(e=>[e.evidence_item_id,snapshot(facts)]));
const body=facts[0].text;
const draft={job_version_id:version,fact_snapshot_hash:snapshot(facts),language:'zh',resume_sections:[{section_id:'s1',title:'项目经历',body}],cover_letter:null,claims:[{claim_id:'c1',output_section_id:'s1',start:0,end:Array.from(body).length,claim_text:body,fact_ids:[facts[0].id],jd_requirement_ids:['r0'],transformation:'verbatim'}],change_summary:[],questions_for_user:[],warnings:[]};
const tests=[];
function test(name,fn){try{fn();tests.push({name,passed:true});}catch(e){tests.push({name,passed:false,error:e.message});}}
const copy=x=>structuredClone(x),scores=(j=job,f=facts,c=confirmations)=>scoreJob(j,f,user,c);
const confirmedFor=f=>Object.fromEntries(job.evidence.items.map(e=>[e.evidence_item_id,snapshot(f)]));
test('score/full-match',()=>assert.equal(scores().route,'HIGH_MATCH'));
test('score/no-send-permission',()=>assert.equal(scores().submission_permission,false));
test('score/unreviewed-mapping',()=>assert.equal(scores(job,facts,{}).route,'NEEDS_INFO'));
test('score/unconfirmed-fact',()=>{const f=copy(facts);f[0].status='unconfirmed';assert.equal(scores(job,f,confirmedFor(f)).route,'NEEDS_INFO');});
test('score/hard-fail-wins',()=>{const j=copy(job),f=copy(facts);j.evidence.items[0].evidence_state='unsupported';j.evidence.items[0].match_level=0;f[0].polarity='negative';assert.equal(scores(j,f,confirmedFor(f)).route,'BLOCKED');});
test('score/no-negative-proof',()=>{const j=copy(job);j.evidence.items[0].evidence_state='unsupported';j.evidence.items[0].match_level=0;assert.throws(()=>scores(j),/NEGATIVE_PROOF/);});
test('score/must-have-hard-rule-cannot-be-removed',()=>{const j=copy(job);j.rules.hard_checks=[];assert.throws(()=>scores(j),/MUST_HAVE_HARD_COVERAGE/);});
test('score/duplicate-hard-requirement',()=>{const j=copy(job);j.rules.hard_checks.push({...j.rules.hard_checks[0],rule_id:'h2'});assert.throws(()=>scores(j),/DUPLICATE_HARD_REQUIREMENT/);});
test('score/negative-fact-cannot-support',()=>{const f=copy(facts);f[0].polarity='negative';assert.throws(()=>scores(job,f,confirmedFor(f)),/POSITIVE_PROOF/);});
test('score/unknown-upper-bound',()=>{const j=copy(job);j.evidence.items[5].evidence_state='unknown';j.evidence.items[5].match_level=null;const s=scores(j);assert.deepEqual([s.score_low,s.score_high,s.coverage],[90,100,.9]);});
test('score/jd-missing-dimensions',()=>{const j=copy(job);j.jd.requirements=j.jd.requirements.slice(0,3);j.evidence.items=j.evidence.items.slice(0,3);j.rules.items=j.rules.items.slice(0,3);const s=scores(j);assert.deepEqual([s.score_low,s.score_high,s.coverage,s.route],[70,100,.7,'REVIEW']);});
test('score/partial-hard-is-unknown',()=>{const j=copy(job);j.evidence.items[0].evidence_state='partial';j.evidence.items[0].match_level=.75;assert.equal(scores(j).route,'NEEDS_INFO');});
test('score/stale-confirmation',()=>{const f=copy(facts);f[0].text+='修改';assert.equal(scores(job,f).route,'NEEDS_INFO');});
test('score/conflict',()=>{const f=copy(facts);f[1].status='conflict';assert.equal(scores(job,f,confirmedFor(f)).route,'NEEDS_INFO');});
test('score/weight-error',()=>{const j=copy(job);j.rules.items[0].weight=31;assert.throws(()=>scores(j),/DIMENSION_WEIGHTS/);});
test('score/duplicate-requirement',()=>{const j=copy(job);j.rules.items[1].requirement_id='r0';assert.throws(()=>scores(j),/RULE_COVERAGE/);});
test('score/wrong-span',()=>{const j=copy(job);j.jd.requirements[0].source_span.quote='Java';assert.throws(()=>scores(j),/JD_SPAN/);});
test('score/foreign-fact',()=>{const f=copy(facts);f[0].user_id=other;assert.throws(()=>scores(job,f),/OWNERSHIP/);});
test('score/inferred-hard-rule',()=>{const j=copy(job);j.jd.requirements[0].certainty='inferred';assert.throws(()=>scores(j),/INFERRED_HARD_RULE/);});
test('score/duplicate-evidence',()=>{const j=copy(job);j.evidence.items[1].evidence_item_id='e0';assert.throws(()=>scores(j),/DUPLICATE_EVIDENCE/);});
test('draft/title-facts-need-human',()=>{const d=copy(draft);d.resume_sections[0].title='某大厂技术总监经历';assert.equal(reviewDraft(d,facts,user,job.section_projects).verdict,'NEEDS_HUMAN');});
test('draft/project-binding-required',()=>assert.equal(reviewDraft(draft,facts,user,{}).verdict,'BLOCKED'));
test('draft/missing-title',()=>{const d=copy(draft);d.resume_sections[0].title=' ';assert.equal(reviewDraft(d,facts,user,job.section_projects).verdict,'BLOCKED');});
test('draft/verbatim-pass',()=>assert.equal(reviewDraft(draft,facts,user,job.section_projects).verdict,'PASS_VERBATIM'));
test('draft/stale-snapshot',()=>{const d=copy(draft);d.fact_snapshot_hash='a'.repeat(64);assert.throws(()=>reviewDraft(d,facts,user),/STALE/);});
test('draft/uncovered-claim',()=>{const d=copy(draft);d.resume_sections[0].body+=' Java';assert.equal(reviewDraft(d,facts,user,job.section_projects).verdict,'BLOCKED');});
test('draft/cross-project',()=>assert.equal(reviewDraft(draft,facts,user,{s1:'project-b'}).verdict,'BLOCKED'));
function revised(text,kind='rephrase',refs=[facts[0].id]){const d=copy(draft);d.resume_sections[0].body=text;Object.assign(d.claims[0],{end:Array.from(text).length,claim_text:text,transformation:kind,fact_ids:refs});return d;}
test('draft/responsibility-inflation',()=>assert.equal(reviewDraft(revised('主导 Python 数据清洗'),facts,user,job.section_projects).verdict,'BLOCKED'));
test('draft/new-tool',()=>assert.equal(reviewDraft(revised('熟练 Java'),facts,user,job.section_projects).verdict,'BLOCKED'));
test('draft/new-number',()=>assert.equal(reviewDraft(revised('处理 300 条记录'),facts,user,job.section_projects).verdict,'BLOCKED'));
test('draft/number-substring',()=>{const f=copy(facts);f[0].text='处理 300 条记录';const d=revised('处理 30 条记录');d.fact_snapshot_hash=snapshot(f);assert.equal(reviewDraft(d,f,user,job.section_projects).verdict,'BLOCKED');});
test('draft/phone-is-not-achievement',()=>{const f=copy(facts);f[0].text='电话 300';f[0].kind='contact';const d=revised('处理 300 条记录');d.fact_snapshot_hash=snapshot(f);assert.equal(reviewDraft(d,f,user,job.section_projects).verdict,'BLOCKED');});
test('draft/rephrase-still-needs-human',()=>assert.equal(reviewDraft(revised('使用 Python 清洗数据'),facts,user,job.section_projects).verdict,'NEEDS_HUMAN'));
test('draft/false-verbatim',()=>assert.equal(reviewDraft(revised('高级 Python','verbatim'),facts,user,job.section_projects).verdict,'BLOCKED'));
test('draft/negative-context-not-excerpted',()=>{const f=copy(facts);f[0].text='未主导 Python 数据清洗';const d=revised('主导 Python 数据清洗','verbatim');d.fact_snapshot_hash=snapshot(f);assert.equal(reviewDraft(d,f,user,job.section_projects).verdict,'BLOCKED');});
test('draft/unconfirmed-source',()=>{const f=copy(facts);f[0].status='unconfirmed';const d=copy(draft);d.fact_snapshot_hash=snapshot(f);assert.equal(reviewDraft(d,f,user,job.section_projects).verdict,'BLOCKED');});
test('draft/forbidden-sensitive-kind',()=>{const f=copy(facts);f[0].kind='government_id';const d=copy(draft);d.fact_snapshot_hash=snapshot(f);assert.equal(reviewDraft(d,f,user,job.section_projects).verdict,'BLOCKED');});
test('draft/unicode-codepoint',()=>{const f=copy(facts);f[0].text='🍍参与课程项目';const d=revised(f[0].text,'verbatim');d.fact_snapshot_hash=snapshot(f);assert.equal(reviewDraft(d,f,user,job.section_projects).verdict,'PASS_VERBATIM');});
const patch={user_id:user,base_artifact_hash:digest(draft),fact_snapshot_hash:snapshot(facts),changes:[{section_id:'s1',new_body:body,new_claims:draft.claims}]};
test('patch/new-version-no-permission',()=>{const before=digest(facts),r=patchDraft(draft,patch,facts,user,job.section_projects);assert.equal(r.external_approval,null);assert.equal(r.preview_binding,null);assert.equal(digest(facts),before);});
test('patch/stale-rejected',()=>{const p=copy(patch);p.base_artifact_hash='a'.repeat(64);assert.throws(()=>patchDraft(draft,p,facts,user),/STALE/);});
test('patch/forbidden-path',()=>assert.throws(()=>patchDraft(draft,{...patch,approvals:['allow']},facts,user),/FORBIDDEN/));
test('patch/unknown-section',()=>{const p=copy(patch);p.changes[0].section_id='facts';assert.throws(()=>patchDraft(draft,p,facts,user),/PATCH_SECTION/);});
test('patch/duplicate-section',()=>assert.throws(()=>patchDraft(draft,{...patch,changes:[patch.changes[0],patch.changes[0]]},facts,user),/PATCH_CHANGES/));
const event=(n,stage,time,app=id(50),sup=null)=>({id:id(100+n),user_id:user,application_id:app,stage,occurred_at:time,supersedes_id:sup});
let events=[];for(const e of [event(1,'SELF_REPORTED_SUBMITTED','2026-09-01T00:00:00Z'),event(2,'INTERVIEW','2026-09-05T00:00:00Z'),event(3,'REJECTED','2026-09-10T00:00:00Z')])events=addManualEvent(events,e,user,'2026-09-15T00:00:00Z');
test('events/replay-idempotent',()=>assert.equal(addManualEvent(events,event(1,'SELF_REPORTED_SUBMITTED','2026-09-01T00:00:00Z'),user).length,3));
test('events/conflicting-replay',()=>assert.throws(()=>addManualEvent(events,event(1,'OFFER','2026-09-01T00:00:00Z'),user),/EVENT_ID_CONFLICT/));
test('events/no-official-receipt',()=>assert.throws(()=>addManualEvent([],event(4,'ACCEPTED','2026-09-01T00:00:00Z'),user),/OFFICIAL/));
test('events/no-cross-user',()=>assert.throws(()=>addManualEvent([],{...event(4,'INTERVIEW','2026-09-01T00:00:00Z'),user_id:other},user),/OWNERSHIP/));
test('events/future-rejected',()=>assert.throws(()=>addManualEvent([],event(4,'INTERVIEW','2099-09-01T00:00:00Z'),user),/FUTURE/));
test('events/invalid-date-rejected',()=>assert.throws(()=>addManualEvent([],event(4,'INTERVIEW','2026-02-30T00:00:00Z'),user),/INVALID_TIME/));
test('cohort/interview-then-reject',()=>{const m=cohortMetrics(events,user,'2026-10-03T00:00:00Z');assert.equal(m.ever_interviewed,1);assert.equal(m.mature,1);assert.equal(m.reply_rate,0);});
test('cohort/pending-not-denominator',()=>assert.equal(cohortMetrics(events,user,'2026-09-20T00:00:00Z').interview_rate,null));
test('cohort/late-event-asof',()=>{let es=addManualEvent([],event(1,'SELF_REPORTED_SUBMITTED','2026-09-01T00:00:00Z'),user,'2026-09-01T00:00:00Z');es=addManualEvent(es,event(2,'INTERVIEW','2026-09-05T00:00:00Z'),user,'2026-10-05T00:00:00Z');assert.equal(cohortMetrics(es,user,'2026-10-03T00:00:00Z').ever_interviewed,0);assert.equal(cohortMetrics(es,user,'2026-10-06T00:00:00Z').ever_interviewed,1);});
test('cohort/correction-recomputes',()=>{const es=addManualEvent(events,event(4,'NO_UPDATE','2026-09-05T00:00:00Z',id(50),id(102)),user,'2026-09-15T00:00:00Z');assert.equal(cohortMetrics(es,user,'2026-10-03T00:00:00Z').ever_interviewed,0);});
test('events/double-correction',()=>{const es=addManualEvent(events,event(4,'NO_UPDATE','2026-09-05T00:00:00Z',id(50),id(102)),user);assert.throws(()=>addManualEvent(es,event(5,'NO_UPDATE','2026-09-05T00:00:00Z',id(50),id(102)),user),/ALREADY_SUPERSEDED/);});
test('cohort/unknown-separate',()=>{const es=addManualEvent(events,event(4,'SUBMISSION_UNKNOWN','2026-09-02T00:00:00Z',id(51)),user,'2026-09-15T00:00:00Z');assert.equal(cohortMetrics(es,user,'2026-10-03T00:00:00Z').unknown,1);});
test('cohort/duplicate-input-rejected',()=>assert.throws(()=>cohortMetrics([...events,events[0]],user,'2026-10-03T00:00:00Z'),/DUPLICATE/));
const key=crypto.randomBytes(32),secret={text:'私密演示经历',user_id:user};
test('vault/authenticated-roundtrip',()=>assert.deepEqual(decryptState(encryptState(secret,key),key),secret));
test('vault/no-cleartext',()=>assert.ok(!JSON.stringify(encryptState(secret,key)).includes(secret.text)));
test('vault/wrong-key',()=>assert.throws(()=>decryptState(encryptState(secret,key),crypto.randomBytes(32)),/AUTHENTICATION/));
test('vault/tampered-data',()=>{const r=encryptState(secret,key),b=Buffer.from(r.data,'base64');b[0]^=1;r.data=b.toString('base64');assert.throws(()=>decryptState(r,key),/AUTHENTICATION/);});
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'job-agent-v03-test-'));fs.chmodSync(temp,0o700);
test('vault/atomic-store-and-audit',()=>{const dir=path.join(temp,'case');withVault(dir,key,s=>({action:'init',output:true}),{audit:[],user_id:user});const s=decryptState(JSON.parse(fs.readFileSync(path.join(dir,'case.enc.json'))),key);assert.equal(s.audit.length,1);assert.equal(fs.statSync(path.join(dir,'case.enc.json')).mode&0o077,0);});
test('vault/lock-prevents-second-writer',()=>{const dir=path.join(temp,'case'),lock=path.join(dir,'.lock');fs.writeFileSync(lock,'', {mode:0o600});assert.throws(()=>withVault(dir,key,()=>({action:'read'})),/CASE_LOCKED/);fs.unlinkSync(lock);});
test('vault/key-permissions',()=>{const f=path.join(temp,'bad-key');fs.writeFileSync(f,key,{mode:0o644});assert.throws(()=>readKey(f),/KEY_PERMISSIONS/);});
const script=path.resolve('skills/job-search-agent/scripts/job-agent.mjs'),keyfile=path.join(temp,'key'),caseDir=path.join(temp,'cli');
const run=(cmd,args=[])=>spawnSync(process.execPath,[script,cmd,...args],{encoding:'utf8'});
const common=['--case',caseDir,'--key-file',keyfile];
test('cli/keygen-and-init',()=>{assert.equal(run('keygen',['--out',keyfile]).status,0);assert.equal(run('init',[...common,'--user',user]).status,0);});
const bundle={user_id:user,facts:facts.map(f=>({...f,status:'unconfirmed'})),jobs:[job]};const input=path.join(temp,'bundle.json');fs.writeFileSync(input,JSON.stringify(bundle));
test('cli/import-candidates',()=>assert.equal(run('import',[...common,'--input',input]).status,0));
test('cli/unconfirmed-route',()=>{const r=run('score',[...common,'--job',jobid]);assert.equal(r.status,0);assert.equal(JSON.parse(r.stdout).route,'NEEDS_INFO');});
test('cli/confirmation-and-score',()=>{for(const f of facts)assert.equal(run('confirm-fact',[...common,'--id',f.id]).status,0);for(const e of job.evidence.items)assert.equal(run('confirm-evidence',[...common,'--job',jobid,'--item',e.evidence_item_id]).status,0);assert.equal(JSON.parse(run('score',[...common,'--job',jobid]).stdout).route,'HIGH_MATCH');});
test('cli/confirmed-import-rejected',()=>{const dir=path.join(temp,'bad-import');assert.equal(run('init',['--case',dir,'--key-file',keyfile,'--user',user]).status,0);fs.writeFileSync(input,JSON.stringify({...bundle,facts}));assert.notEqual(run('import',['--case',dir,'--key-file',keyfile,'--input',input]).status,0);});
test('cli/no-submit-command',()=>assert.notEqual(run('submit',common).status,0));
test('cli/no-secret-error-output',()=>{const r=run('score',[...common,'--job','private-identifier']);assert.ok(!r.stderr.includes('private-identifier'));});
test('cli/key-must-be-separate',()=>{const r=run('inspect',['--case',caseDir,'--key-file',path.join(caseDir,'key')]);assert.ok(r.stderr.includes('KEY_MUST_BE_SEPARATE'));});
const report={scope:'actual_local_prototype_functions_and_cli_synthetic_data_only',node:process.version,runtime_sha256:digest(fs.readFileSync(script,'utf8')),test_sha256:digest(fs.readFileSync(path.resolve('prototype-tests/run.mjs'),'utf8')),schema_sha256:digest(fs.readFileSync(path.resolve('model-contracts.schema.json'),'utf8')),total:tests.length,passed:tests.filter(t=>t.passed).length,tests};
fs.writeFileSync('prototype-tests/results.json',JSON.stringify(report,null,2)+'\n');
const fixtureBundle={...bundle,facts:bundle.facts,jobs:[job]};fs.writeFileSync('prototype-fixtures/candidate-bundle.json',JSON.stringify(fixtureBundle,null,2)+'\n');
fs.writeFileSync('prototype-fixtures/confirmed-material-draft.json',JSON.stringify(draft,null,2)+'\n');
console.log(`${report.passed}/${report.total} actual prototype tests passed`);for(const t of tests.filter(t=>!t.passed))console.log('FAIL',t.name,t.error);process.exitCode=report.passed===report.total?0:1;
